# Generated by Django 6.0.3 on 2026-03-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya_',
            },
        ),
    ]
