# Generated by Django 6.0.3 on 2026-03-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Yozuvchi F.I.SH')),
                ('bio', models.TextField(verbose_name='Yozuvchi  haqida ')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Yozuvchi  rasmi ')),
            ],
            options={
                'verbose_name': 'Author_',
            },
        ),
    ]
