# Generated by Django 6.0.3 on 2026-03-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Yozuvchi  rasmi '),
        ),
    ]
